export const userData =[
    {
        id: 123,
        userType: "userType",
        fullName: "fullName",
        userName: "userName",
        email:"email",
        useSystem: "useSystem",
        password: "password",
        confirmPassword: "confirmPassword",
        userGroup: "userGroup",
        inviteUser: "inviteUser",
    },
    {
        id: 345,
        userType: "userType",
        fullName: "fullName",
        userName: "userName",
        email:"email",
        useSystem: "useSystem",
        password: "password",
        confirmPassword: "confirmPassword",
        userGroup: "userGroup",
        inviteUser: "inviteUser",
    },
    {
        id: 554,
        userType: "userType",
        fullName: "fullName",
        userName: "userName",
        email:"email",
        useSystem: "useSystem",
        password: "password",
        confirmPassword: "confirmPassword",
        userGroup: "userGroup",
        inviteUser: "inviteUser",
    }
]